site_name: Swift OAuth2 Client
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
          setup_commands:
            - import sys
            - sys.path.append("src")
nav:
  - Home: index.md
  - API Reference: api_reference.md